gk_meta:
  name: GK Meta
  attributes:
    physical.agility: 0.014640
    goal_keeping.reflexes: 0.012837
    goal_keeping.aerial_reach: 0.011812
    goal_keeping.throwing: 0.007465
    goal_keeping.handling: 0.006255
    goal_keeping.rushing_out: -0.003310
    mental.composure: 0.007436
    mental.decisions: 0.005089

dlr_meta:
  name: DLR Meta
  attributes:
    physical.pace: 0.018991
    physical.jumping_reach: 0.014582
    physical.acceleration: 0.012670
    mental.anticipation: 0.012269
    mental.concentration: 0.009911
    technical.dribbling: 0.008246
    mental.composure: 0.007720
    technical.crossing: 0.006812

dc_meta:
  name: DC Meta
  attributes:
    physical.jumping_reach: 0.022608
    physical.pace: 0.015882
    physical.acceleration: 0.013536
    mental.work_rate: 0.010819
    mental.anticipation: 0.010326
    mental.positioning: 0.008864
    technical.passing: 0.008826
    mental.concentration: 0.008358

wblr_meta:
  name: WBLR Meta
  attributes:
    physical.pace: 0.019196
    physical.acceleration: 0.018585
    physical.jumping_reach: 0.013761
    mental.composure: 0.011762
    mental.vision: 0.010025
    technical.crossing: 0.009596
    mental.work_rate: 0.008166
    mental.determination: 0.005121

dmc_meta:
  name: DMC Meta
  attributes:
    physical.acceleration: 0.020572
    mental.anticipation: 0.013047
    physical.stamina: 0.010352
    physical.jumping_reach: 0.009796
    mental.composure: 0.009470
    technical.passing: 0.009114
    technical.long_shots: 0.007952
    technical.dribbling: 0.007338

mlr_meta:
  name: MLR Meta
  attributes:
    physical.pace: 0.020497
    technical.dribbling: 0.014018
    physical.acceleration: 0.012883
    mental.composure: 0.012072
    mental.vision: 0.011542
    physical.jumping_reach: 0.011150
    technical.crossing: 0.010598
    physical.stamina: 0.009658

mc_meta:
  name: MC Meta
  attributes:
    mental.anticipation: 0.014011
    physical.acceleration: 0.012595
    mental.composure: 0.012589
    physical.pace: 0.012156
    technical.crossing: 0.010100
    technical.dribbling: 0.008134
    physical.jumping_reach: 0.007918
    physical.strength: 0.006528

amlr_meta:
  name: AMLR Meta
  attributes:
    physical.pace: 0.023458
    physical.acceleration: 0.019640
    mental.anticipation: 0.015160
    technical.crossing: 0.014857
    technical.dribbling: 0.013533
    physical.jumping_reach: 0.013029
    technical.technique: 0.012662
    mental.composure: 0.012295

amc_meta:
  name: AMC Meta
  attributes:
    physical.pace: 0.016763
    physical.acceleration: 0.016348
    mental.concentration: 0.013697
    mental.composure: 0.012813
    technical.technique: 0.011647
    technical.long_shots: 0.009914
    physical.jumping_reach: 0.009524
    technical.dribbling: 0.008679

stc_meta:
  name: STC Meta
  attributes:
    physical.jumping_reach: 0.020557
    physical.pace: 0.020096
    physical.acceleration: 0.014496
    mental.concentration: 0.013675
    physical.balance: 0.012043
    technical.dribbling: 0.010739
    mental.vision: 0.009392
    mental.composure: 0.009161

gk_ml:
  name: GK ML
  attributes:
    physical.agility: 0.012505
    goal_keeping.aerial_reach: 0.011164
    goal_keeping.reflexes: 0.010801
    mental.composure: 0.006723
    goal_keeping.handling: 0.006410
    goal_keeping.throwing: 0.006367
    goal_keeping.rushing_out: -0.006245
    physical.pace: 0.004643

dlr_ml:
  name: DLR ML
  attributes:
    physical.acceleration: 0.013597
    physical.jumping_reach: 0.013060
    physical.pace: 0.012236
    mental.anticipation: 0.011565
    physical.agility: 0.009327
    technical.first_touch: 0.008223
    mental.composure: 0.007745
    mental.concentration: 0.007133

dc_ml:
  name: DC ML
  attributes:
    physical.jumping_reach: 0.019070
    physical.acceleration: 0.015935
    physical.agility: 0.012246
    mental.positioning: 0.010717
    mental.concentration: 0.010560
    mental.anticipation: 0.008858
    mental.vision: 0.008293
    mental.flair: 0.007868

wblr_ml:
  name: WBLR ML
  attributes:
    physical.pace: 0.017325
    mental.anticipation: 0.012306
    physical.jumping_reach: 0.011456
    mental.composure: 0.011074
    physical.agility: 0.010540
    technical.technique: 0.009274
    physical.acceleration: 0.008873
    technical.dribbling: 0.008574

dmc_ml:
  name: DMC ML
  attributes:
    physical.pace: 0.014999
    physical.acceleration: 0.013865
    mental.off_the_ball: 0.012342
    mental.anticipation: 0.010224
    physical.jumping_reach: 0.008530
    technical.passing: 0.008060
    mental.vision: 0.007703
    mental.work_rate: 0.007163

mlr_ml:
  name: MLR ML
  attributes:
    physical.pace: 0.021969
    physical.acceleration: 0.016877
    mental.anticipation: 0.016714
    mental.off_the_ball: 0.015771
    technical.passing: 0.013718
    technical.dribbling: 0.010168
    technical.crossing: 0.008961
    physical.jumping_reach: 0.008427

mc_ml:
  name: MC ML
  attributes:
    physical.pace: 0.016960
    technical.dribbling: 0.012320
    physical.acceleration: 0.010894
    mental.composure: 0.010411
    mental.anticipation: 0.010086
    mental.vision: 0.009814
    technical.crossing: 0.009064
    physical.jumping_reach: 0.006533

amlr_ml:
  name: AMLR ML
  attributes:
    physical.pace: 0.025619
    physical.acceleration: 0.017786
    mental.vision: 0.015335
    technical.technique: 0.014416
    technical.dribbling: 0.014384
    technical.crossing: 0.010459
    physical.jumping_reach: 0.009989
    mental.concentration: 0.009832

amc_ml:
  name: AMC ML
  attributes:
    physical.pace: 0.019289
    physical.acceleration: 0.018151
    mental.anticipation: 0.015457
    technical.technique: 0.015131
    technical.passing: 0.012255
    mental.concentration: 0.009733
    technical.long_shots: 0.009488
    physical.jumping_reach: 0.007665

stc_ml:
  name: STC ML
  attributes:
    physical.pace: 0.021277
    mental.anticipation: 0.013547
    physical.jumping_reach: 0.013172
    physical.agility: 0.011111
    technical.dribbling: 0.010546
    technical.crossing: 0.009884
    mental.concentration: 0.009881
    physical.balance: 0.007499
