jvf_4141_positive_fludity_v1:
  - game_gk_sweeper_keeper_attack
  - game_dl_dr_inverted_wing_back_support
  - game_dc_ball_playing_defender_defend
  - game_dc_central_defender_defend
  - game_dl_dr_inverted_wing_back_support
  - game_dmc_deep_lying_playmaker_defend
  - game_aml_amr_inside_forward_attack
  - game_amc_attacking_midfielder_support
  - game_amc_advanced_playmaker_support
  - game_aml_amr_winger_attack
  - game_stc_complete_forward_attack
